### ISSUE TITLE
Audio call using rtm service?

### ISSUE THREAD

**Issue by Linspirit98** [AgoraIO/Agora-Flutter-RTM-SDK#101]
Is it possible to have audio call using rtm service？Are there any examples?

**Comment by LichKing-2234** [comment]
using for calling invitation?

**Comment by Linspirit98** [comment]
Yes. I want to start an audio call one or multiple user in the channel. I know rtc engine can achieve this, but is there a way to start audio call using rtm? because I need to use the private/public message function in rtm; I want to achieve both functions using only rtm.

**Comment by LichKing-2234** [comment]
You should use RTC + RTM.
