### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AgoraRtm_iOS"

### ISSUE THREAD

**Issue by panchalAlpit** [AgoraIO/Agora-Flutter-RTM-SDK#103]
[!] CocoaPods could not find compatible versions for pod "AgoraRtm_iOS":
  In snapshot (Podfile.lock):
    AgoraRtm_iOS (= 1.2.2)

  In Podfile:
    agora_rtm (from `.symlinks/plugins/agora_rtm/ios`) was resolved to 1.0.0, which depends on
      AgoraRtm_iOS (= 1.4.8)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `AgoraRtm_iOS` inside your development pod `agora_rtm`.
   You should run `pod update AgoraRtm_iOS` to apply changes you've made.
   
 After the update the flutter getting the above issue, So How can I fix this issue?
 Please help

**Comment by LichKing-2234** [comment]
pls follow the log, run pod update AgoraRtm_iOS
