### ISSUE TITLE
PlatformException(4, not supported, null, null)

### ISSUE THREAD

**Issue by panchalAlpit** [AgoraIO/Agora-Flutter-RTM-SDK#105]
I/SurfaceView( 3244): onWindowVisibilityChanged(0) true io.agora.rtc.video.ViEAndroidGLES20{2905a02 V.E...... ......I. 0,0-0,0} of ViewRootImpl@839d277[MainActivity]
I/SurfaceControl( 3244): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x26f1f13 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@839d277[MainActivity]( 3244): Relayout returned: old=(0,0,1080,2102) new=(0,0,1080,2102) req=(1080,2102)0 dur=12 res=0x7 s={true -5476376615979056144} ch=true fn=-1
I/SurfaceView( 3244): windowStopped(false) true io.agora.rtc.video.ViEAndroidGLES20{2905a02 V.E...... ......ID 0,0-1080,2102} of ViewRootImpl@839d277[MainActivity]
I/SurfaceView( 3244): surfaceCreated 1 #8 io.agora.rtc.video.ViEAndroidGLES20{2905a02 V.E...... ......ID 0,0-1080,2102}
I/SurfaceView( 3244): surfaceChanged (1080,2102) 1 #8 io.agora.rtc.video.ViEAndroidGLES20{2905a02 V.E...... ......ID 0,0-1080,2102}
I/AGORA_SDK( 3244): Surface changed to width 1080 height 2102
I/SurfaceView( 3244): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@6ae144e surfaceControl = Surface(name=SurfaceView - Sys2030:com.legit/com.legit.MainActivity@2905a02@0)/@0x4a2996f frame = 1
E/flutter ( 3244): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] **Unhandled Exception: PlatformException(4, not supported, null, null)**
E/flutter ( 3244): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 3244): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 3244): <asynchronous suspension>
E/flutter ( 3244): #2      _LLHostScreenState._initAgoraRtcEngine (package:legit/LLAgora/LLHostScreen.dart:141:5)
E/flutter ( 3244): <asynchronous suspension>
E/flutter ( 3244): #3      _LLHostScreenState.initialize (package:legit/LLAgora/LLHostScreen.dart:128:5)
E/flutter ( 3244): <asynchronous suspension>
E/flutter ( 3244): 
E/AGORA_SDK( 3244): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK( 3244): cannot open log file for writing: agorartm.log, err=30

@LichKing-2234 Please help me.

**Comment by LichKing-2234** [comment]
which method you called?

**Comment by panchalAlpit** [comment]
@LichKing-2234 The Error is showing the below bold line.
 
 `   Future<void> _initAgoraRtcEngine() async {
 
      _engine = await RtcEngine.create(LLConfig.appId);
      
       await _engine.enableVideo();
       
       await _engine.enableLocalAudio(true);
       
        **await _engine.setClientRole(ClientRole.Broadcaster);**
        
     }
  `

**Comment by LichKing-2234** [comment]
this is the method of RTC SDK

**Comment by LichKing-2234** [comment]
you should set channel profile to livebroadcasting first.
