### ISSUE TITLE
Issue With Sending Invites

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO/Agora-Flutter-RTM-SDK#107]
So I have an issue when I send an invite and it's accepted. Then when the call is ended If the app is still opened without restarting I call the same person and send another invite it then receives an error code of 3.

**Comment by LichKing-2234** [comment]
could you pls provide the SDK log?

**Comment by rlee1990** [comment]
@LichKing-2234 I have provided the app with write permission.

**Comment by rlee1990** [comment]
@LichKing-2234 The issue I'm having is I don't see any docs on setting the log file for rtm

**Comment by rlee1990** [comment]
@LichKing-2234 here are the log files
[agorartm.log](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/files/7347307/agorartm.log)
[agorartm (1).log](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/files/7347308/agorartm.1.log)

**Comment by LichKing-2234** [comment]
the error means this invitation is time out.

**Comment by rlee1990** [comment]
@LichKing-2234 anything on this?

**Comment by LichKing-2234** [comment]
Ok, I will test it by your comment.
