### ISSUE TITLE
Can not launch app because of agora rtm plugin error

### ISSUE THREAD

**Issue by RalphLincoln** [AgoraIO/Agora-Flutter-RTM-SDK#111]
I always get this error
Could not find rtm-sdk-1.4.7.jar(com.github.agorabuilder:rrm-sdk:1.4.7)

**Comment by leofx** [comment]
Mine is too, has your problem been solve
![333](https://user-images.githubusercontent.com/27850030/137575334-5851f869-0311-486e-99e0-6bdf72d279aa.png)
d?

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/blob/master/android/build.gradle#L24

**Comment by LichKing-2234** [comment]
pls add this config

**Comment by LichKing-2234** [comment]
if not working, pls remove "www."

**Comment by leofx** [comment]
@LichKing-2234 
Modified, still unable to download.
![911](https://user-images.githubusercontent.com/27850030/137576640-b6fc8eaf-d50a-4be4-aefc-295b6ff36a2d.png)
![3333](https://user-images.githubusercontent.com/27850030/137576657-ac678582-6ae2-4c7c-a184-9ce14b8e3116.png)

**Comment by sanal1291** [comment]
> if not working, pls remove "www."

I removed www and its working fine now (android/build.gradle)

**Comment by leofx** [comment]
Upgrade flutter version to 2.5 and then modify the "android/build.gradle" file, modify line 24, and modify it to "maven {url'https://jitpack.io'}"

**Comment by LichKing-2234** [comment]
@leofx your link is wrong, pls replace ' https to 'http

**Comment by Dakrain** [comment]
Hello I am facing a same issue. 
![image](https://user-images.githubusercontent.com/39589783/137616868-c8627203-4fd2-454e-848e-b602767ae826.png)
Flutter doctor 
![image](https://user-images.githubusercontent.com/39589783/137616895-bc0c9f78-3e1a-40d6-9197-d20a02d37cdf.png)

**Comment by Dakrain** [comment]
> @Dakrain Configure this **android/build.gradle** ![99911](https://user-images.githubusercontent.com/27850030/137617375-f9eb0981-023d-4fff-9ebd-955845281812.png)

Yes, I try http, https, remove www. still not working.
![image](https://user-images.githubusercontent.com/39589783/137619651-a95fb711-0438-42d6-97f7-daef46650f3c.png)

**Comment by leofx** [comment]
@Dakrain You need to restart your project

**Comment by Dakrain** [comment]
> @Dakrain You need to restart your project

I try to restart the project, clean project and still no hope :(

**Comment by ajith-m-doodlebug** [comment]
> The problem is not in your project files but here in this Agora Flutter RTM SDK.
> 
> I have created a fork with this fix that all users can use.
> 
> You have to change this in your pubspec.yml: #agora_rtm: ^1.0.1 agora_rtm: git: url: git://github.com/ThinkBIG-Company/Agora-Flutter-RTM-SDK.git
> 
> This should make it work.
> 
> Cheers ^_^

I used this, and still not able to build the application.

**Comment by maravilhosinga** [comment]
Hello, the solution is to change.
This is the only working solution in 2022

from: `api 'com.github.agorabuilder:rtm-sdk:1.4.7'`
to: `api 'io.agora.rtm:rtm-sdk:1.4.10'`

**Comment by ThinkBIG-Company** [comment]
> > Hello, the solution is to change. This is the only working solution in 2022
> > from: `api 'com.github.agorabuilder:rtm-sdk:1.4.7'` to: `api 'io.agora.rtm:rtm-sdk:1.4.10'`
> 
> Hey but where should i find this line to change ??

android/build.gradle bottom

**Comment by XxThunderBlastxX** [comment]
> > > Hello, the solution is to change. This is the only working solution in 2022
> > > from: `api 'com.github.agorabuilder:rtm-sdk:1.4.7'` to: `api 'io.agora.rtm:rtm-sdk:1.4.10'`
> > 
> > 
> > Hey but where should i find this line to change ??
> 
> android/build.gradle bottom

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


This is my build.gradle file but i cant find any dependencies or line where i can change :(

**Comment by ThinkBIG-Company** [comment]
You have to change this in your pubspec.yml:
#agora_rtm:
agora_rtm:
  git:
    url: git://github.com/ThinkBIG-Company/Agora-Flutter-RTM-SDK.git

This should make it work.

**Comment by XxThunderBlastxX** [comment]
> You have to change this in your pubspec.yml: #agora_rtm: agora_rtm: git: url: git://github.com/ThinkBIG-Company/Agora-Flutter-RTM-SDK.git
> 
> This should make it work.

yeah i tried this also but, still not working :|

**Comment by mark-heyylife** [comment]
I face the same issue

**Comment by LichKing-2234** [comment]
The latest version has fixed this issue.
https://pub.dev/packages/agora_rtm/versions/1.1.0

**Comment by FeifanChang** [comment]
> The latest version has fixed this issue. https://pub.dev/packages/agora_rtm/versions/1.1.0

Solved my problem
