### ISSUE TITLE
iOS Xcode build Error

### ISSUE THREAD

**Issue by zhangweiwei0326** [AgoraIO/Agora-Flutter-RTM-SDK#113]
Error output from Xcode build:
    error: the following command failed with exit code 0 but produced no further output
     Returns the result of the [loginByToken]([AgoraRtmKit loginByToken:user:completion:]) method call. <p><i>errorCode:<i> Login error code. See AgoraRtmLoginErrorCode.
     Returns the result of the [loginByToken]([AgoraRtmKit loginByToken:user:completion:]) method call. <p><i>errorCode:<i> Login error code. See AgoraRtmLoginErrorCode.
     Indicates the results of calling the [logoutWithCompletion]([AgoraRtmKit logoutWithCompletion:]) method call. <p><i>errorCode:<i> Logout error code. See AgoraRtmLogoutErrorCode.
     Indicates the results of calling the [logoutWithCompletion]([AgoraRtmKit logoutWithCompletion:]) method call. <p><i>errorCode:<i> Logout error code. See AgoraRtmLogoutErrorCode.
     Returns the result of the [sendMessage]([AgoraRtmKit sendMessage:toPeer:completion:]) method call. <p><i>errorCode:<i> Error code of sending the peer-to-peer message. See AgoraRtmSendPeerMessageErrorCode.
     Returns the result of the [sendMessage]([AgoraRtmKit sendMessage:toPeer:completion:]) method call. <p><i>errorCode:<i> Error code of sending the peer-to-peer message. See AgoraRtmSendPeerMessageErrorCode.
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
     Returns the result of the [loginByToken]([AgoraRtmKit loginByToken:user:completion:]) method call. <p><i>errorCode:<i> Login error code. See AgoraRtmLoginErrorCode.
     Returns the result of the [loginByToken]([AgoraRtmKit loginByToken:user:completion:]) method call. <p><i>errorCode:<i> Login error code. See AgoraRtmLoginErrorCode.
     Indicates the results of calling the [logoutWithCompletion]([AgoraRtmKit logoutWithCompletion:]) method call. <p><i>errorCode:<i> Logout error code. See AgoraRtmLogoutErrorCode.
     Indicates the results of calling the [logoutWithCompletion]([AgoraRtmKit logoutWithCompletion:]) method call. <p><i>errorCode:<i> Logout error code. See AgoraRtmLogoutErrorCode.
     Returns the result of the [sendMessage]([AgoraRtmKit sendMessage:toPeer:completion:]) method call. <p><i>errorCode:<i> Error code of sending the peer-to-peer message. See AgoraRtmSendPeerMessageErrorCode.
     Returns the result of the [sendMessage]([AgoraRtmKit sendMessage:toPeer:completion:]) method call. <p><i>errorCode:<i> Error code of sending the peer-to-peer message. See AgoraRtmSendPeerMessageErrorCode.
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmGetUserAttributesBlock)(NSArray< AgoraRtmAttribute *> * _Nullable attributes, NSString * userId, AgoraRtmProcessAttributeErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
    typedef void (^AgoraRtmChannelMemberCountBlock)(NSArray<AgoraRtmChannelMemberCount *> * channelMemberCounts, AgoraRtmChannelMemberCountErrorCode errorCode);
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error launching application on iPhone 13.

MacBook-Pro-2:ios weiwei$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

**Comment by LichKing-2234** [comment]
works on the latest version
