### ISSUE TITLE
AgoraRtcEngine.setLogFile("/abc.log") is not creating any log and getting an issue as "invalid file path for libcolorx-loader.so"

### ISSUE THREAD

**Issue by VaniLokesh** [AgoraIO/Agora-Flutter-RTM-SDK#114]
Hello i am new to agora and i am trying to keep SDK logs for Agora and getting the issue as "invalid file path for libcolorx-loader.so" . can anyone guide me through this? Thank you

**Comment by LichKing-2234** [comment]
you should set the full absolute path.
