### ISSUE TITLE
sendLocalInvitation not properly documented

### ISSUE THREAD

**Issue by ameerfayiz** [AgoraIO/Agora-Flutter-RTM-SDK#115]
i cant find any proper documentation for sendLocalInvitation(Map<dynamic, dynamic> arguments) .. what all arguments are to be passed as argument for the method?? 

sendLocalInvitation(
{
    "calleeId ": 19198,
    "channelId":"<channelName>", 
    "content":"-----"}
)

is giving me error :

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: sendLocalInvitation failed errorCode:1
E/flutter (15740): #0      AgoraRtmClient.sendLocalInvitation (package:agora_rtm/src/agora_rtm_client.dart:442:7)
E/flutter (15740): <asynchronous suspension>
E/flutter (15740): #1      _MyAppState.inviteCall (package:call_test2/main.dart:47:5)
E/flutter (15740): <asynchronous suspension>

**Comment by LichKing-2234** [comment]
Pls refer to https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/blob/3e43e362da024cdbe390b102f09178be77971b7b/example/lib/main.dart#L330

**Comment by ameerfayiz** [comment]
> Pls refer to
> 
> https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/blob/3e43e362da024cdbe390b102f09178be77971b7b/example/lib/main.dart#L330

Thanks for your quick response. really appreciated . this is exactly what i was searching for.
