### ISSUE TITLE
AgoraRTMClient : Create client failed errorCode:-1

### ISSUE THREAD

**Issue by nicholastch92** [AgoraIO/Agora-Flutter-RTM-SDK#117]
Only happens when using WiFI on iOS. 

If I switch off WiFI and use cellular data, it is able to create the instance perfectly.

May I know is internet issue unable to connect to Agora server?

**Comment by LichKing-2234** [comment]
is your WiFi connection working?

**Comment by nicholastch92** [comment]
Yes it is working one.

I found out it might be the iOS IPV6 issue. Because same apps, same source code, when install on Android it works.

But when it is on IOS, it is not working.
