### ISSUE TITLE
What is the maximum number of occupants allowed in group chat?

### ISSUE THREAD

**Issue by aytunch** [AgoraIO/Agora-Flutter-RTM-SDK#119]
I could not find any info on the documentation (free tier)

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Real-time-Messaging/faq/rtm_concurrency

**Comment by aytunch** [comment]
Thanks you @LichKing-2234 
So even in free tier there is no limit on the number of occupants but just a limit on number of messages sent per second.
got it.
