### ISSUE TITLE
能否升级一下底层的sdk，需要用二进制消息包

### ISSUE THREAD

**Issue by wildfire810** [AgoraIO/Agora-Flutter-RTM-SDK#12]
您好，是这样，请问可以更新一下底层的依赖库吗？
我这边对二进制消息包的功能有需求。
谢谢。

**Comment by plutoless** [comment]
我们会尽快安排升级，但可能还是需要一点时间，这边如果改动不大 也可以帮忙提个PR

**Comment by wildfire810** [comment]
谢谢，很乐意贡献。不过老实说，目前这边业务比较紧。国内企业的通病了。所以如果你们有计划，我就不做和你们可能重复的事情了。如果之后时间合适了，可以多沟通。
你们新版本升级的api就比老版本帮多了。以前甩出来回调，还得自己用completer。

**Comment by wildfire810** [comment]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':agora_rtm' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0

您看，目前还出现了这样一个问题

**Comment by LichKing-2234** [comment]
supported it
