### ISSUE TITLE
Login Error 

### ISSUE THREAD

**Issue by egnimos** [AgoraIO/Agora-Flutter-RTM-SDK#125]
Unhandled Exception: login failed errorCode:5

@plutoless  Iam also facing the same issue..., I have followed all the instruction provided in agora doc

but I'am getting the login failed error with error code-5

but, I have seen some message regarding agora

```
Access denied finding property "net.dns1"
[        ] E/libc    (17063): Access denied finding property "net.dns2"
[        ] E/libc    (17063): Access denied finding property "net.dns3"
[   +1 ms] E/libc    (17063): Access denied finding property "net.dns4"
[   +2 ms] W/ample.big_buddy(17063): type=1400 audit(0.0:37): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=5161
scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0

```

how can I resolve this
Thanku

_Originally posted by @egnimos in https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/issues/124#issuecomment-1100651686_

**Comment by LichKing-2234** [comment]
have you double-checked appId or token?

**Comment by Genialngash** [comment]
any solution?
