### ISSUE TITLE
Support the new Agora Chat API

### ISSUE THREAD

**Issue by aytunch** [AgoraIO/Agora-Flutter-RTM-SDK#129]
https://docs.agora.io/en/agora-chat/landing-page?platform=iOS

As far as I understand, Agora is transitioning to the new Chat API from the RTM API.
When can we use Chat API in Flutter? Is there a repo for it currently that we can try out?

**Comment by rlee1990** [comment]
@aytunch you might want to check [this](https://docs.agora.io/en/agora-chat/agora_chat_get_started_flutter?platform=Flutter)

**Comment by LichKing-2234** [comment]
Sorry, we have no plan for it at now
