### ISSUE TITLE
 RtmEngine.setLocalUserAttributes failed errorCode:3

### ISSUE THREAD

**Issue by Leeuuong** [AgoraIO/Agora-Flutter-RTM-SDK#130]
很显然，当前版本(agora_rtm: ^1.1.1)下，setLocalUserAttributes 方法不可用

**Comment by LichKing-2234** [comment]
可以尝试下最新版本

**Comment by LichKing-2234** [comment]
setLocalUserAttributes的参数，因为没有定义类型，可以参考原始代码的取值来组装map

https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/blob/master/android/src/main/kotlin/io/agora/agorartm/AgoraRtmPlugin.kt#L344
