### ISSUE TITLE
Defective OpenSSL Version

### ISSUE THREAD

**Issue by conan1150** [AgoraIO/Agora-Flutter-RTM-SDK#137]
Defective OpenSSL Version
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:

OpenSSL 1.1.1h in lib/x86_64/libagora-rtm-sdk-jni.so

Android publish to store.
  agora_rtm: 1.1.1

https://support.google.com/faqs/answer/12576638

**Comment by FeifanChang** [comment]
same problem

**Comment by LichKing-2234** [comment]
The latest version has fixed it.
