### ISSUE TITLE
iOS crashed when app in background for a while

### ISSUE THREAD

**Issue by akindone** [AgoraIO/Agora-Flutter-RTM-SDK#138]
**Describe the bug**
put app in background for about 2 hours, then open the phone found app crashed. we got a crash report from testflight.
using agora_rtm: ^1.1.1

**Screenshots**
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/17843738/206103425-0588ad21-71fa-413f-bed4-e4b8b485a47d.png">

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/17843738/206103610-1d5b566a-3dce-4f0c-af63-3c0feaa909d0.png)

**Additional context**

**Comment by HatsuneMikuV** [comment]
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x28171dbc0> was mutated while being enumerated.'
![image](https://user-images.githubusercontent.com/14038743/230445314-259d0313-f49f-4e6a-8f80-99d63d5e3ccb.png)

**Comment by HatsuneMikuV** [comment]
![image](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/assets/14038743/cabe6c00-8122-49d2-88fd-dc7fcfba2a4b)

**Comment by LichKing-2234** [comment]
has been fixed at the latest version
