### ISSUE TITLE
RTM failed to login

### ISSUE THREAD

**Issue by creative-hustlers** [AgoraIO/Agora-Flutter-RTM-SDK#139]
**Describe the bug**
When we are trying to login into RTM sdk its gives error code 2, I have generated token from console, tried both temp token and token generated by user id but same result, I have also tried to login by passing token as null as shown in example but no luck.

```
login failed errorCode:2
AgoraRtmClient.login (package:agora_rtm/src/agora_rtm_client.dart:229:7)
<asynchronous suspension>
```

I have used following latest dependency version

agora_rtm: ^1.5.0

**Comment by ahmed3670-art** [comment]
same error

**Comment by devmike01** [comment]
Has anyone found a solution to this problem? Please

**Comment by Princewil** [comment]
Any solution yet?

**Comment by LichKing-2234** [comment]
have you double-checked your appId and token? BTW pls try the latest version.
