### ISSUE TITLE
Crash in destroy client

### ISSUE THREAD

**Issue by senkia24** [AgoraIO/Agora-Flutter-RTM-SDK#151]
**Describe the bug**
```

      await _rtmChannel?.leave();
      await _rtmChannel?.release();
      await _rtmClient?.logout();
      await _rtmClient?.release();
```
sometimes crashed my app.

flutter version 3.10.5, rtm version 1.5.5

**Smartphone (please complete the following information):**
 - Device: Iphone 12 pro max
 - OS: 17.0

**Comment by LichKing-2234** [comment]
any crash dump?
