### ISSUE TITLE
AgoraRtmLocalInvitation Error

### ISSUE THREAD

**Issue by Beartx** [AgoraIO/Agora-Flutter-RTM-SDK#153]
I am getting the following error when running my app, It seems as dependancy incompatibility 

Users/.pub-cache/hosted/pub.dev/agora_uikit-1.3.3/lib/controllers/rtm_client_event_handler.dart:76:7: Error: A value of type 'Null Function(LocalInvitation)' can't be assigned to a variable of type 'dynamic Function(LocalInvitation, String)?'.
- 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/Users/.pub-cache/hosted/pub.dev/agora_rtm-1.5.5/lib/src/utils.dart').
utils.dart:1
      (AgoraRtmLocalInvitation invitation) {
      ^

/Users/.pub-cache/hosted/pub.dev/agora_uikit-1.3.3/lib/controllers/rtm_client_event_handler.dart:81:7: Error: A value of type 'void Function(LocalInvitation)' can't be assigned to a variable of type 'void Function(LocalInvitation, String)?'.
- 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/Users/.pub-cache/hosted/pub.dev/agora_rtm-1.5.5/lib/src/utils.dart').
utils.dart:1
      (AgoraRtmLocalInvitation invitation) {
      ^

Target kernel_snapshot failed: Exception

this are the dependancies:
firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  country_picker: ^2.0.20
  image_picker: ^0.8.7+4
  flutter_riverpod: ^2.3.5
  flutter_contacts: ^1.1.6
  uuid: ^3.0.6
  intl: ^0.17.0
  cached_network_image: 
  cached_video_player: 
  emoji_picker_flutter: ^1.3.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  audioplayers: 
  swipe_to: ^1.0.2
  agora_uikit: ^1.3.3
  url_launcher: ^6.1.11

and I am using this sdk version
sdk: '>=2.18.1 <3.0.0'

**Comment by LichKing-2234** [comment]
seem like it is an issue from uikit

**Comment by Beartx** [comment]
Well it's obvious from agora-uikit, I tried different version, yet I get same issue

**Comment by LichKing-2234** [comment]
pls move to here https://github.com/AgoraIO-Community/VideoUIKit-Flutter
