### ISSUE TITLE
ios crash EXC_BAD_ACCESS (SIGSEGV), subtype = KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by manishapaghadar** [AgoraIO/Agora-Flutter-RTM-SDK#154]
I use Agora RTM and Agora RTC engine. I am getting a crash related to AgoraRtmKit when I close the app in release mode.  While, in android I am not getting any crash on closing the app.  
On dispose method of a Main screen I have logged out Agora Rtm client. I also tested the app by removing the code of logging out Agora Rtm Client. It gives the same crash.

![Screenshot 2023-07-11 at 7 50 33 PM](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/assets/95341949/8fbbb2cc-278c-4ce6-99a4-2202e528382f)

Flutter Doctor details:
![Screenshot 2023-07-11 at 7 58 15 PM 1](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/assets/95341949/cc5d2932-356a-495a-9e68-46ecbd2fed5b)

Testing devices: iPhone 13, iPhone 14

**Comment by Mo0Khaled** [comment]
same here, did you found any solutions?

**Comment by Mo0Khaled** [comment]
also on IOS, did you try it on IOS?
 it gives me the same crash!

**Comment by manishapaghadar** [comment]
@Mo0Khaled, not yet, if you found any solution, please share it here.

**Comment by LichKing-2234** [comment]
fixed at 1.5.7
