### ISSUE TITLE
Sent messages to the same channel from the web SDK aren't received 

### ISSUE THREAD

**Issue by ahmdaeyz** [AgoraIO/Agora-Flutter-RTM-SDK#163]
**Describe the bug**
Sent messages to the same channel from the web SDK aren't received 

**To Reproduce**
1. Use the v1 version of web sdk  
2. Create a channel and join it
3. Use `this` SDK, create a channel and join it 
4. The web sdk receives this sdk joined the channel
5. This sdk prints the web joined via RTMChannel.getMembers()
6. Send message from the web sdk
7. This sdk doesn't recieve it 
8. Send a message from this sdk 
9. The web receives it 

**Expected behavior**
Messages sent from any platform to a channel should be received to all users regardless of the platform 

**Desktop (please complete the following information):**
 - OS: macOs (latest)
 - Browser: Brave
 - Version:  1.62.165 Chromium: 121.0.6167.184 

**Smartphone (please complete the following information):**
 - Device: Simulator of iOS 17 and Iphone 14 
 - OS: Latest

**Comment by hanieljazzar** [comment]
I can confirm having the same issue. This is a major one, hope it gets investigated soon
