### ISSUE TITLE
subscribe/unsubscribe PeersOnlineStatus

### ISSUE THREAD

**Issue by casti** [AgoraIO/Agora-Flutter-RTM-SDK#33]
Hello, I'm looking at the latest Android and IOS API and I
see subscribePeersOnlineStatus and unsubscribePeersOnlineStatus methods but not on Flutter-RTM. Is there any scheduled update to the Flutter RTM?

**Comment by LichKing-2234** [comment]
@casti We will update it before Q3

**Comment by casti** [comment]
> @casti We will update it before Q3

Thank you for response.

**Comment by sowsan** [comment]
Any update on this feature?

**Comment by gaoyueban** [comment]
PeersOnlineStatus 大概会在什么时候开发完成？

**Comment by LichKing-2234** [comment]
Supported it
