### ISSUE TITLE
Update Native RTM SDK (1.4.0+)

### ISSUE THREAD

**Issue by gocal** [AgoraIO/Agora-Flutter-RTM-SDK#47]
Agora Native SDK has been updated to 1.4.0 version, so it also should be update in this project

https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_iOS_v1_4_0.zip
https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_Android_v1_4_0.zip

**Comment by LichKing-2234** [comment]
We will support it, but not too soon, because there is no human resource at the moment, and we will be happy if you can contribute code🙂

**Comment by gocal** [comment]
I've updated native SDK dependecies, and all the main functionalities work as expected. Still the new file/image upload functions should be verified, so I will keep you posted once I have a little bit more time to test it and create PR.

If anyone else is interested - the update is available at https://github.com/gocal/Flutter-RTM/tree/update_native_rtm_sdk_1_4_1

**Comment by wheel1992** [comment]
> https://github.com/gocal/Flutter-RTM/tree/update_native_rtm_sdk_1_4_1

Hi @gocal , I've managed to pull your git repo to my project. However, after `flutter clean` and `flutter pub get`, my app still show the Local Network permission even though RTM SDK 1.4.1 and above will not show if we did not specify `NSLocalNetworkUsageDescription`

**Comment by gocal** [comment]
Hi @wheel1992, please check Agora documentation - https://docs.agora.io/en/All/faq/local_network_privacy, I hope that helps.

**Comment by nholmvio** [comment]
Hello...thanks all for the work on this. Looks like it may still be in work, so any ETA on when the image upload APIs flutter support will be available in a release on pub.dev?  Just looking at how to prioritize feature dev.   Thank you.

**Comment by TBoonkwan** [comment]
Your lib does not support null safety?

**Comment by LichKing-2234** [comment]
The latest version has removed the file/image message.
