### ISSUE TITLE
How to Sent and Receive Image or File Messages

### ISSUE THREAD

**Issue by ghost** [AgoraIO/Agora-Flutter-RTM-SDK#58]
How to sent and receive image or file message with Agora-Flutter-RTM-SDK? I can't find the way in document, and want some help. Thanks.

**Comment by LichKing-2234** [comment]
you can follow this issue https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/issues/47

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
