### ISSUE TITLE
E/AGORA_SDK(17294): cannot open log file for writing: agorartm.log, err=30

### ISSUE THREAD

**Issue by faizansahab05** [AgoraIO/Agora-Flutter-RTM-SDK#60]
Hello, can someone tell me how I can resolve this issue?
I want to sent and receive messages on the chat screen. I am using Agora RTM SDK.

///CREATING CLIENT
void _createClient() async {
    _client =
        await AgoraRtmClient.createInstance("19dbf56713624f4bbfbba4f10e02acf6");
    _client.onMessageReceived = (AgoraRtmMessage message, String peerId) {
      _log("Peer msg: " + peerId + ", msg: " + message.text);
    };
    _client.onConnectionStateChanged = (int state, int reason) {
      _log('Connection state changed: ' +
          state.toString() +
          ', reason: ' +
          reason.toString());
      if (state == 5) {
        _client.logout();
        _log('Logout.');
        setState(() {
          _isLogin = false;
        });
      }
    };

    userId = '6';

    try {
      await _client.login(null, userId);
      _log('_client.login Success: ' + userId);
    } catch (errorCode) {
      _log('_client.login error: ' + errorCode.toString());
    }
  }

///SENDING MESSAGE TO PEER
void _toggleSendPeerMessage() async {
    // String uid = await UserUtils.idFromCache();
    String peerUid = userId;
    String text = textBoxController.text;
    if (text.isEmpty) {
      _log('Please input text to send.');
      return;
    }

    try {
      AgoraRtmMessage message = AgoraRtmMessage.fromText(text);
      _log(message.text);
      _log('Sending peer message. = > peerUid = $peerUid, message = $message');
      await _client
          .sendMessageToPeer(peerUid, message, false)
          .then((sendResult) {
        {
          _log('Send peer message success.');
          setState(() {
            chatList.add(MSG("${textBoxController.text}"));
            textBoxController.clear();
          });

        }
      });
      _log('Send peer message success.');
    } catch (errorCode) {
      _log('Send peer message error: ' + errorCode.toString());
    }
  }

**Comment by plutoless** [comment]
it seems you are lacking of permission to write to disk file. please ensure you grant proper privilege.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
