### ISSUE TITLE
Show Send or Receive Call Screen to user

### ISSUE THREAD

**Issue by DineshTaral123** [AgoraIO/Agora-Flutter-RTM-SDK#61]
I want to show incoming call screen with accept and reject call button when app is in background.

**Comment by LichKing-2234** [comment]
maybe you should use Callkit and ConnectionService?

**Comment by DineshTaral123** [comment]
i already tried with [callkeep](https://pub.dev/packages/callkeep) package, it opens the default incoming call screen of the device  but when i click the receive call button it starts the call like a normal call, i need to open my app and perform some tasks when user pick the call. I try to customise the code and but it not worked for me.
