### ISSUE TITLE
login failed errorCode:5

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [AgoraIO/Agora-Flutter-RTM-SDK#62]
I have created account in agora.io and got the appid from it and now if i am trying to login it returns

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: login failed errorCode:5
#0      AgoraRtmClient.login (package:agora_rtm/src/agora_rtm_client.dart:228:7)
<asynchronous suspension>

```
I checked in the api reference its says invalid token.

below is my code for login..

```
_client = await AgoraRtmClient.createInstance(Constant.AGORA_APP_ID);
_client.onMessageReceived = (AgoraRtmMessage message, String peerId) {
  _log(user: peerId, info: message.text, type: 'message');
};
_client.onConnectionStateChanged = (int state, int reason) {
  if (state == 5) {
    _client.logout();
    //_log('Logout.');
    setState(() {
      _isLogin = false;
    });
  }
};
await _client.login(null, widget.channelName);
_channel = await _createChannel(widget.channelName);
await _channel.join();

```

i tried in demo in that i was using the key provided in the demo but while i switched to my new key it gives above error.

**Comment by nhank-group** [comment]
I have the same issue. So I tried import to my project. I got crashed on iOS
`Thread 1: "-[NSNull cStringUsingEncoding:]: unrecognized selector sent to instance 0x205e38a00"`

**Comment by nhan7777** [comment]
I have same issue. I don't know how to fix

**Comment by LichKing-2234** [comment]
the error code 5 means your token is invalid.
https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_oc/Constants/AgoraRtmLoginErrorCode.html

**Comment by BhavyKoshti9spl** [comment]
@LichKing-2234 i know there is invalid token but how do i get the token in the demo token field is passed as null and by that key i was able to run the start stream and here i just changed the `APP_ID` in my code, is it makes this vast difference ?

And how i am gonna get the token for that?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Real-time-Messaging/rtm_token?platform=Android

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.

**Comment by mnikamApero** [comment]
I have facing same errorCode 5 for login . i had passed appId but still facing same error.Any idea to solve this error.

**Comment by BhavyKoshti9spl** [comment]
@mnikamApero  create a new project on agora and this time select low security where you can see by only appid you can create and generate the live session and able to login as well also in the code pass null for token.

**Comment by mnikamApero** [comment]
@BhavyKoshti9spl  thanks. working fine.
