### ISSUE TITLE
Not found [createLocalInvitation() for android] and  [initWithCalleeId() for iOS]

### ISSUE THREAD

**Issue by DineshTaral123** [AgoraIO/Agora-Flutter-RTM-SDK#63]
i want open a incoming call screen. As per the AgoraRTM documentation i found there have two function to appear incoming call screen, [createLocalInvitation() for android] and [initWithCalleeId() for iOS] but i don't found both function in the Agora RTM repo.

**Comment by plutoless** [comment]
agora rtm do not contain UI. if you need call screen you will need to make it yourself or use callkit.

**Comment by LichKing-2234** [comment]
we have called these methods on the internal of Flutter layer, so you only need to call `sendLocalInvitation` method.

**Comment by DineshTaral123** [comment]
> we have called these methods on the internal part of the Flutter layer, so you only need to call `sendLocalInvitation` method.

Thanks for quick reply.
i try to call "sendLocalInvitation" but it taking parameter type of <Map<dynamic,dynamic>>, what parameters i need to send in this method ?

**Comment by LichKing-2234** [comment]
you can refer to the native code.
![image](https://user-images.githubusercontent.com/9312526/110589244-15cec900-81b1-11eb-8924-01ceb495a7f7.png)

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
