### ISSUE TITLE
Channel Operation flag enableNotificationToChannelMembers is not working correctly on ios

### ISSUE THREAD

**Issue by michaelchiowong** [AgoraIO/Agora-Flutter-RTM-SDK#64]
Hi, Agora team,

The current version of agora flutter RTM channel operations on below functions is not working on IOS, but is working on Android. 
No matter the value of enableNotificationToChannelMembers is true or false, on IOS, it is always notifying all memebers in the channel.

  Future<void> addOrUpdateChannelAttributes(
      String channelId,
      List<AgoraRtmChannelAttribute> attributes,
      bool enableNotificationToChannelMembers)

  Future<void> deleteChannelAttributesByKeys(String channelId,
      List<String> keys, bool enableNotificationToChannelMembers) 

------------------
michael-mac:$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H114, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

• No issues found!

**Comment by michaelchiowong** [comment]
any team members reply?

Thanks.

**Comment by LichKing-2234** [comment]
sorry for the later reply, could you pls provide the SDK log?

**Comment by RoJoHub** [comment]
> any team members reply?
> 
> Thanks.

Hi friends. There is indeed this problem. Please wait for the next release, we will fix this problem.
