### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by statsss** [AgoraIO/Agora-Flutter-RTM-SDK#65]
Migrate to null safety   Agora-Flutter-RTM-SDK ?

**Comment by LichKing-2234** [comment]
not in the plan now, I will comment here if it in the plan.

**Comment by Dersh** [comment]
Thanks. Waiting very much!

**Comment by bhavin-concetto** [comment]
@LichKing-2234  can I add PR?

**Comment by LichKing-2234** [comment]
@bhavin-concetto Sure:smile:

**Comment by bhavin-concetto** [comment]
@LichKing-2234  can you publish with pre-release and NullSafety Tag?

**Comment by LichKing-2234** [comment]
@bhavin-concetto yes, I will publish it today.

**Comment by LichKing-2234** [comment]
published 1.0.0-rc.0
