### ISSUE TITLE
What the difference between this plugin and agora_rtc_engine's streamMessage

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-RTM-SDK#67]
I just wondering should i use this plugin with agora_rtc_engine since i can see similiar function to handle realtime message?

why i thought it was same is when i look at one of agora_rtc_engine's function, it was `sendStreamMessage` that can be handled on `streamMessage`, i can't find the difference especially there is no further documentation or notes on agora_rtc_engine about this function

**Comment by plutoless** [comment]
@nizwar rtm is basically more reliable and suitable for signaling delivery. sendStreamMessage utilize stream channel of video, it's handy but not as reliable as RTM.

**Comment by nizwar** [comment]
Thankyou for your information then
