### ISSUE TITLE
Image & File Support

### ISSUE THREAD

**Issue by iamdineshkumar** [AgoraIO/Agora-Flutter-RTM-SDK#69]
I just went through code but there is no codes releated to Images & Files whether its under progress or when it can be expected?

**Comment by plutoless** [comment]
how about use an OSS to upload your files/image, and use RTM to transfer the url of the files? that's usually more recommended.

**Comment by iamdineshkumar** [comment]
Any recommended service providers ?

**Comment by plutoless** [comment]
aws s3 for example. there're lots of options available.

**Comment by toklive** [comment]
Given that the RTM SDK supports this feature any update on when it is available with flutter ? https://docs.agora.io/en/Real-time-Messaging/upload_download_media_oc?platform=iOS

**Comment by iamdineshkumar** [comment]
@LichKing-2234  As @toklive  told both platform Android & iOS supports media sharing features. so support for same provided in flutter will be awesome. This will avoid using another service provider to host files and share media.

**Comment by mandreshope** [comment]
any update for this issue please ?

**Comment by LichKing-2234** [comment]
In the latest version, this feature is not supported yet.

**Comment by tashigeekyants** [comment]
Wondering why is this issue closed @LichKing-2234  . [Agora RTM](https://pub.dev/packages/agora_rtm) still does not support media.

**Comment by LichKing-2234** [comment]
@tashigeekyants at the last version of RTM, media supported has been removed.

**Comment by tashigeekyants** [comment]
@LichKing-2234 okay, just wondering why it has been removed. I need media support along with text in the my agora chat application.
