### ISSUE TITLE
Does Agora support user mentioning?

### ISSUE THREAD

**Issue by NaagAlgates** [AgoraIO/Agora-Flutter-RTM-SDK#72]
I would like to know if the SDK supports when any of the users is mentioned by his/her name in the chat section? 

For e.g. Consider that I'm in a channel with 50 other users. I wanted to mention a user by their name (@ symbol followed by their mobile number)  and then type my message and submit.

**Comment by plutoless** [comment]
i think you will need to do this by you own.
