### ISSUE TITLE
Does Agora support editing the message.

### ISSUE THREAD

**Issue by NaagAlgates** [AgoraIO/Agora-Flutter-RTM-SDK#74]
I'm exploring the SDK and I'm curious to know whether the SDK supports message editing? 

I'm sure I can edit the text from my UI but how does it gets updated in the backend in Agora? Is there any listener for that?

**Comment by LichKing-2234** [comment]
we can send a message, but not support edit the history message.

**Comment by LichKing-2234** [comment]
You can implement it with your server.
