### ISSUE TITLE
Is there an option to check the delivery report?

### ISSUE THREAD

**Issue by NaagAlgates** [AgoraIO/Agora-Flutter-RTM-SDK#76]
I would like to know if there is any way to fetch the message delivery status?

**Comment by LichKing-2234** [comment]
do you want to get the log about every message delivery status?

**Comment by NaagAlgates** [comment]
status after calling `sendMessage` would be fine at this stage.

**Comment by LichKing-2234** [comment]
sendMessage will return Future, calling then means success.
