### ISSUE TITLE
Missing files in x86_64

### ISSUE THREAD

**Issue by rmj-s** [AgoraIO/Agora-Flutter-RTM-SDK#79]
Does this library supports `x86_64`? Our app is crashing with `java.lang.UnsatisfiedLinkError`, when we unpacked the `APK` and checked the directories we found that `libagora-rtm-sdk-jni.so` is missing in `x86_64` directory.

**Comment by plutoless** [comment]
what kind of device are you using?

**Comment by rmj-s** [comment]
This issue has been reported on `Samsung Galaxy A21s, Google Pixel 3 XL, Google Pixel 4 XL`.

**Comment by LichKing-2234** [comment]
implementation 'io.agora.rtm:rtm-sdk:1.2.2' not support x86_64 yet.
so you need to upgrade to the 1.4.2 version, but may cause some build error, should modify some code on kotlin layer.

**Comment by Vasques1995** [comment]
Any news regarding this error?

**Comment by LichKing-2234** [comment]
fixed it
