### ISSUE TITLE
abiFilters 'armeabi-v7a' is missing in the example

### ISSUE THREAD

**Issue by nilsreichardt** [AgoraIO/Agora-Flutter-RTM-SDK#82]
## Description
You describe in your `README.md` that you should add `abiFilters 'armeabi-v7a'` into `build.gradle`:

> Agora RTM sdk contain arm64 architecture, but Flutter is not shipping “libflutter.so” in arm64 currently. You need add "abiFilters" in *build.gradle* if you need build release apk.

```
android {
    ..
    defaultConfig {
        ..
         ndk {
             abiFilters 'armeabi-v7a'
        }
        ..
    }
    ..
}
```

But I can't find this in your [example](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/tree/master/example).

**Comment by LichKing-2234** [comment]
the readme is out of date. I will remove it.
