### ISSUE TITLE
Error: MissingPluginException(No implementation found for method createInstance on channel io.agora.rtm)

### ISSUE THREAD

**Issue by gusmondel** [AgoraIO/Agora-Flutter-RTM-SDK#86]
After doing all the setup of the example and adding my appId, the error appears: Error: MissingPluginException (No implementation found for method createInstance on channel io.agora.rtm)

**Comment by LichKing-2234** [comment]
seem like you should uninstall the app and reinstall it.

**Comment by gusmondel** [comment]
I have executed it in app and on the web and it is always the same error, it also happens to my work team when they try to execute the example code

**Comment by gusmondel** [comment]
I use the package null safety

**Comment by LichKing-2234** [comment]
it not support web.

**Comment by gusmondel** [comment]
my problem is the same on app!! Android and IOS :/

**Comment by LichKing-2234** [comment]
which example?
