### ISSUE TITLE
Flutter - Specify AreaCode in RTM

### ISSUE THREAD

**Issue by Komal-Khairnar** [AgoraIO/Agora-Flutter-RTM-SDK#87]
Hello, I am developing a Flutter app (ios & android) with Agora RTM in which I need to specify the area of connection (AreaCode). Is there any way to do that?

**Comment by LichKing-2234** [comment]
do you mean upgrading native RTM SDK?

**Comment by Komal-Khairnar** [comment]
Agora documentation explains how to do that in native (ios & android). I am using Agora-Flutter-RTM-SDK. Is there any way to  achieve that in flutter rather than doing it in native code.
