### ISSUE TITLE
More Readable status and error codes

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Agora-Flutter-RTM-SDK#88]
<img width="940" alt="Screen Shot 2021-06-01 at 1 15 20 PM" src="https://user-images.githubusercontent.com/60107328/120371434-6ef35800-c2db-11eb-9a54-63ebba773ded.png">

Currently the API returns state and reason as an integer. It would be more readable to return a `ConnectionState` type and some with reason, so that it can be more readable. The if statement would look more like 
`if(state == ConnectionState.aborted)`

**Comment by LichKing-2234** [comment]
good point, it will be optimized next version, but not so far.

**Comment by Dakrain** [comment]
Hello, I am struggle with this too. No document or error code. Just int and int

**Comment by LichKing-2234** [comment]
you can follow the doc about android or ios.

**Comment by LichKing-2234** [comment]
The latest version supports readable status
