### ISSUE TITLE
(IOS) nehelper sent invalid result code [1] for Wi-Fi information request

### ISSUE THREAD

**Issue by AnhTu6610** [AgoraIO/Agora-Flutter-RTM-SDK#91]
[] nehelper sent invalid result code [1] for Wi-Fi information request
flutter: Connection state changed: 2, reason: 1
flutter: Login error: login failed errorCode:9
flutter: Connection state changed: 1, reason: 4
[] nehelper sent invalid result code [1] for Wi-Fi information request
[connection] nw_endpoint_handler_set_adaptive_read_handler [C6.1 2a03:2880:f0ff:e:face:b00c:0:2.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C6.1 2a03:2880:f0ff:e:face:b00c:0:2.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
[tcp] tcp_input [C6.1:3] flags=[R] seq=773477790, ack=0, win=0 state=CLOSED rcv_nxt=773477790, snd_una=3052466986
[tcp] tcp_input [C6.1:3] flags=[R] seq=773477790, ack=0, win=0 state=CLOSED rcv_nxt=773477790, snd_una=3052466986
[tcp] tcp_input [C6.1:3] flags=[R] seq=773477790, ack=0, win=0 state=CLOSED rcv_nxt=773477790, snd_una=3052466986
dnssd_clientstub read_all(15) DEFUNCT
[VERBOSE-2:FlutterObservatoryPublisher.mm(143)] Could not register as server for FlutterObservatoryPublisher. Check your network settings and relaunch the application.
dnssd_clientstub read_all(22) DEFUNCT
[VERBOSE-2:FlutterObservatoryPublisher.mm(143)] Could not register as server for FlutterObservatoryPublisher. Check your network settings and relaunch the application.

**Comment by LichKing-2234** [comment]
maybe you can provide the SDK log file.
