### ISSUE TITLE
AgoraRtmChannel previous messages

### ISSUE THREAD

**Issue by suyashnehete** [AgoraIO/Agora-Flutter-RTM-SDK#93]
We have a project where we have implemented chat using Agora RTM. Is there any way to retrieve AgoraRtmChannel's previous messages?

**Comment by LichKing-2234** [comment]
Not support yet, But we have a plan to support it, maybe in Q4.

**Comment by toklive** [comment]
So at this point the only option is to store the chat in our own database? It is a real limitation :(

**Comment by fldvlpr** [comment]
Any updates on this?

**Comment by isuru19963** [comment]
Still Not Support?

**Comment by SR-INGENIOUSMINDSLAB** [comment]
Any Update on this?

**Comment by LichKing-2234** [comment]
This feature has been removed from the shelves.

https://docs.agora.io/en/signaling/reference/release-notes?platform=android
