### ISSUE TITLE
Flutter 2.5 error pub get 

### ISSUE THREAD

**Issue by amebrahimi** [AgoraIO/Agora-Flutter-RTM-SDK#98]
When trying to pub get android 2.5 there is a problem which is 
```
The plugin `agora_rtm` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Comment by LichKing-2234** [comment]
Do you mean Flutter 2.5?

**Comment by LichKing-2234** [comment]
Seem like it is a warning. I will plan to upgrade it to v2.

**Comment by amebrahimi** [comment]
@LichKing-2234 Yes It's not a warning it wont let me do pub get

**Comment by xOldeVx** [comment]
same problem, I can't use rtm anymore, any date to update?

**Comment by panchalAlpit** [comment]
How can I fix this issue?it's working in android but when I want to update the pod at that time I'm getting the same issue.

**Comment by panchalAlpit** [comment]
@LichKing-2234 Below line I have added. but getting error "Execution failed for task ':app:compileDebugKotlin'",

Added:-     GeneratedPluginRegistrant.registerWith(this)

**Comment by LichKing-2234** [comment]
@panchalAlpit you should not add `GeneratedPluginRegistrant.registerWith(this)` when using v2.

**Comment by panchalAlpit** [comment]
After upgrade the plugin it's working.
